# Permalinks
permalink:           pretty

# Setup
title:               Andrew T Lytle
tagline:             ""
url:                 http://atlytle.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Andrew Lytle
  url:               https://twitter.com/atlytle
  email:             

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/atlytle/atlytle.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
